/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "message.pb-c.h"
void   nebula__param__init
                     (Nebula__Param         *message)
{
  static Nebula__Param init_value = NEBULA__PARAM__INIT;
  *message = init_value;
}
size_t nebula__param__get_packed_size
                     (const Nebula__Param *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__param__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__param__pack
                     (const Nebula__Param *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__param__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__param__pack_to_buffer
                     (const Nebula__Param *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__param__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__Param *
       nebula__param__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__Param *)
     protobuf_c_message_unpack (&nebula__param__descriptor,
                                allocator, len, data);
}
void   nebula__param__free_unpacked
                     (Nebula__Param *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__param__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__account_update_request__init
                     (Nebula__AccountUpdateRequest         *message)
{
  static Nebula__AccountUpdateRequest init_value = NEBULA__ACCOUNT_UPDATE_REQUEST__INIT;
  *message = init_value;
}
size_t nebula__account_update_request__get_packed_size
                     (const Nebula__AccountUpdateRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__account_update_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__account_update_request__pack
                     (const Nebula__AccountUpdateRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__account_update_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__account_update_request__pack_to_buffer
                     (const Nebula__AccountUpdateRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__account_update_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__AccountUpdateRequest *
       nebula__account_update_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__AccountUpdateRequest *)
     protobuf_c_message_unpack (&nebula__account_update_request__descriptor,
                                allocator, len, data);
}
void   nebula__account_update_request__free_unpacked
                     (Nebula__AccountUpdateRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__account_update_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__account_update_response__init
                     (Nebula__AccountUpdateResponse         *message)
{
  static Nebula__AccountUpdateResponse init_value = NEBULA__ACCOUNT_UPDATE_RESPONSE__INIT;
  *message = init_value;
}
size_t nebula__account_update_response__get_packed_size
                     (const Nebula__AccountUpdateResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__account_update_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__account_update_response__pack
                     (const Nebula__AccountUpdateResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__account_update_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__account_update_response__pack_to_buffer
                     (const Nebula__AccountUpdateResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__account_update_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__AccountUpdateResponse *
       nebula__account_update_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__AccountUpdateResponse *)
     protobuf_c_message_unpack (&nebula__account_update_response__descriptor,
                                allocator, len, data);
}
void   nebula__account_update_response__free_unpacked
                     (Nebula__AccountUpdateResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__account_update_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__auth_request__init
                     (Nebula__AuthRequest         *message)
{
  static Nebula__AuthRequest init_value = NEBULA__AUTH_REQUEST__INIT;
  *message = init_value;
}
size_t nebula__auth_request__get_packed_size
                     (const Nebula__AuthRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__auth_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__auth_request__pack
                     (const Nebula__AuthRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__auth_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__auth_request__pack_to_buffer
                     (const Nebula__AuthRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__auth_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__AuthRequest *
       nebula__auth_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__AuthRequest *)
     protobuf_c_message_unpack (&nebula__auth_request__descriptor,
                                allocator, len, data);
}
void   nebula__auth_request__free_unpacked
                     (Nebula__AuthRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__auth_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__auth_response__init
                     (Nebula__AuthResponse         *message)
{
  static Nebula__AuthResponse init_value = NEBULA__AUTH_RESPONSE__INIT;
  *message = init_value;
}
size_t nebula__auth_response__get_packed_size
                     (const Nebula__AuthResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__auth_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__auth_response__pack
                     (const Nebula__AuthResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__auth_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__auth_response__pack_to_buffer
                     (const Nebula__AuthResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__auth_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__AuthResponse *
       nebula__auth_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__AuthResponse *)
     protobuf_c_message_unpack (&nebula__auth_response__descriptor,
                                allocator, len, data);
}
void   nebula__auth_response__free_unpacked
                     (Nebula__AuthResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__auth_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__message__content__init
                     (Nebula__Message__Content         *message)
{
  static Nebula__Message__Content init_value = NEBULA__MESSAGE__CONTENT__INIT;
  *message = init_value;
}
void   nebula__message__init
                     (Nebula__Message         *message)
{
  static Nebula__Message init_value = NEBULA__MESSAGE__INIT;
  *message = init_value;
}
size_t nebula__message__get_packed_size
                     (const Nebula__Message *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__message__pack
                     (const Nebula__Message *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__message__pack_to_buffer
                     (const Nebula__Message *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__Message *
       nebula__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__Message *)
     protobuf_c_message_unpack (&nebula__message__descriptor,
                                allocator, len, data);
}
void   nebula__message__free_unpacked
                     (Nebula__Message *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__message_seq__content__init
                     (Nebula__MessageSeq__Content         *message)
{
  static Nebula__MessageSeq__Content init_value = NEBULA__MESSAGE_SEQ__CONTENT__INIT;
  *message = init_value;
}
void   nebula__message_seq__init
                     (Nebula__MessageSeq         *message)
{
  static Nebula__MessageSeq init_value = NEBULA__MESSAGE_SEQ__INIT;
  *message = init_value;
}
size_t nebula__message_seq__get_packed_size
                     (const Nebula__MessageSeq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__message_seq__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__message_seq__pack
                     (const Nebula__MessageSeq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__message_seq__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__message_seq__pack_to_buffer
                     (const Nebula__MessageSeq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__message_seq__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__MessageSeq *
       nebula__message_seq__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__MessageSeq *)
     protobuf_c_message_unpack (&nebula__message_seq__descriptor,
                                allocator, len, data);
}
void   nebula__message_seq__free_unpacked
                     (Nebula__MessageSeq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__message_seq__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__message_kiev_ack__init
                     (Nebula__MessageKievAck         *message)
{
  static Nebula__MessageKievAck init_value = NEBULA__MESSAGE_KIEV_ACK__INIT;
  *message = init_value;
}
size_t nebula__message_kiev_ack__get_packed_size
                     (const Nebula__MessageKievAck *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__message_kiev_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__message_kiev_ack__pack
                     (const Nebula__MessageKievAck *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__message_kiev_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__message_kiev_ack__pack_to_buffer
                     (const Nebula__MessageKievAck *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__message_kiev_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__MessageKievAck *
       nebula__message_kiev_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__MessageKievAck *)
     protobuf_c_message_unpack (&nebula__message_kiev_ack__descriptor,
                                allocator, len, data);
}
void   nebula__message_kiev_ack__free_unpacked
                     (Nebula__MessageKievAck *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__message_kiev_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__subscribe_request__init
                     (Nebula__SubscribeRequest         *message)
{
  static Nebula__SubscribeRequest init_value = NEBULA__SUBSCRIBE_REQUEST__INIT;
  *message = init_value;
}
size_t nebula__subscribe_request__get_packed_size
                     (const Nebula__SubscribeRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__subscribe_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__subscribe_request__pack
                     (const Nebula__SubscribeRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__subscribe_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__subscribe_request__pack_to_buffer
                     (const Nebula__SubscribeRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__subscribe_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__SubscribeRequest *
       nebula__subscribe_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__SubscribeRequest *)
     protobuf_c_message_unpack (&nebula__subscribe_request__descriptor,
                                allocator, len, data);
}
void   nebula__subscribe_request__free_unpacked
                     (Nebula__SubscribeRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__subscribe_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__subscribe_response__content__init
                     (Nebula__SubscribeResponse__Content         *message)
{
  static Nebula__SubscribeResponse__Content init_value = NEBULA__SUBSCRIBE_RESPONSE__CONTENT__INIT;
  *message = init_value;
}
void   nebula__subscribe_response__init
                     (Nebula__SubscribeResponse         *message)
{
  static Nebula__SubscribeResponse init_value = NEBULA__SUBSCRIBE_RESPONSE__INIT;
  *message = init_value;
}
size_t nebula__subscribe_response__get_packed_size
                     (const Nebula__SubscribeResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__subscribe_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__subscribe_response__pack
                     (const Nebula__SubscribeResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__subscribe_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__subscribe_response__pack_to_buffer
                     (const Nebula__SubscribeResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__subscribe_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__SubscribeResponse *
       nebula__subscribe_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__SubscribeResponse *)
     protobuf_c_message_unpack (&nebula__subscribe_response__descriptor,
                                allocator, len, data);
}
void   nebula__subscribe_response__free_unpacked
                     (Nebula__SubscribeResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__subscribe_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__notify_body__init
                     (Nebula__NotifyBody         *message)
{
  static Nebula__NotifyBody init_value = NEBULA__NOTIFY_BODY__INIT;
  *message = init_value;
}
size_t nebula__notify_body__get_packed_size
                     (const Nebula__NotifyBody *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__notify_body__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__notify_body__pack
                     (const Nebula__NotifyBody *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__notify_body__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__notify_body__pack_to_buffer
                     (const Nebula__NotifyBody *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__notify_body__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__NotifyBody *
       nebula__notify_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__NotifyBody *)
     protobuf_c_message_unpack (&nebula__notify_body__descriptor,
                                allocator, len, data);
}
void   nebula__notify_body__free_unpacked
                     (Nebula__NotifyBody *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__notify_body__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__sms_request__file_info__init
                     (Nebula__SmsRequest__FileInfo         *message)
{
  static Nebula__SmsRequest__FileInfo init_value = NEBULA__SMS_REQUEST__FILE_INFO__INIT;
  *message = init_value;
}
void   nebula__sms_request__init
                     (Nebula__SmsRequest         *message)
{
  static Nebula__SmsRequest init_value = NEBULA__SMS_REQUEST__INIT;
  *message = init_value;
}
size_t nebula__sms_request__get_packed_size
                     (const Nebula__SmsRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__sms_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__sms_request__pack
                     (const Nebula__SmsRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__sms_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__sms_request__pack_to_buffer
                     (const Nebula__SmsRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__sms_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__SmsRequest *
       nebula__sms_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__SmsRequest *)
     protobuf_c_message_unpack (&nebula__sms_request__descriptor,
                                allocator, len, data);
}
void   nebula__sms_request__free_unpacked
                     (Nebula__SmsRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__sms_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__sms_response__init
                     (Nebula__SmsResponse         *message)
{
  static Nebula__SmsResponse init_value = NEBULA__SMS_RESPONSE__INIT;
  *message = init_value;
}
size_t nebula__sms_response__get_packed_size
                     (const Nebula__SmsResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__sms_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__sms_response__pack
                     (const Nebula__SmsResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__sms_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__sms_response__pack_to_buffer
                     (const Nebula__SmsResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__sms_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__SmsResponse *
       nebula__sms_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__SmsResponse *)
     protobuf_c_message_unpack (&nebula__sms_response__descriptor,
                                allocator, len, data);
}
void   nebula__sms_response__free_unpacked
                     (Nebula__SmsResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__sms_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__presence_notify__content__init
                     (Nebula__PresenceNotify__Content         *message)
{
  static Nebula__PresenceNotify__Content init_value = NEBULA__PRESENCE_NOTIFY__CONTENT__INIT;
  *message = init_value;
}
void   nebula__presence_notify__init
                     (Nebula__PresenceNotify         *message)
{
  static Nebula__PresenceNotify init_value = NEBULA__PRESENCE_NOTIFY__INIT;
  *message = init_value;
}
size_t nebula__presence_notify__get_packed_size
                     (const Nebula__PresenceNotify *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__presence_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__presence_notify__pack
                     (const Nebula__PresenceNotify *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__presence_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__presence_notify__pack_to_buffer
                     (const Nebula__PresenceNotify *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__presence_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__PresenceNotify *
       nebula__presence_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__PresenceNotify *)
     protobuf_c_message_unpack (&nebula__presence_notify__descriptor,
                                allocator, len, data);
}
void   nebula__presence_notify__free_unpacked
                     (Nebula__PresenceNotify *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__presence_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__presence_request__init
                     (Nebula__PresenceRequest         *message)
{
  static Nebula__PresenceRequest init_value = NEBULA__PRESENCE_REQUEST__INIT;
  *message = init_value;
}
size_t nebula__presence_request__get_packed_size
                     (const Nebula__PresenceRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__presence_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__presence_request__pack
                     (const Nebula__PresenceRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__presence_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__presence_request__pack_to_buffer
                     (const Nebula__PresenceRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__presence_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__PresenceRequest *
       nebula__presence_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__PresenceRequest *)
     protobuf_c_message_unpack (&nebula__presence_request__descriptor,
                                allocator, len, data);
}
void   nebula__presence_request__free_unpacked
                     (Nebula__PresenceRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__presence_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__presence_response__init
                     (Nebula__PresenceResponse         *message)
{
  static Nebula__PresenceResponse init_value = NEBULA__PRESENCE_RESPONSE__INIT;
  *message = init_value;
}
size_t nebula__presence_response__get_packed_size
                     (const Nebula__PresenceResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__presence_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__presence_response__pack
                     (const Nebula__PresenceResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__presence_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__presence_response__pack_to_buffer
                     (const Nebula__PresenceResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__presence_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__PresenceResponse *
       nebula__presence_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__PresenceResponse *)
     protobuf_c_message_unpack (&nebula__presence_response__descriptor,
                                allocator, len, data);
}
void   nebula__presence_response__free_unpacked
                     (Nebula__PresenceResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__presence_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__account_status_request__init
                     (Nebula__AccountStatusRequest         *message)
{
  static Nebula__AccountStatusRequest init_value = NEBULA__ACCOUNT_STATUS_REQUEST__INIT;
  *message = init_value;
}
size_t nebula__account_status_request__get_packed_size
                     (const Nebula__AccountStatusRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__account_status_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__account_status_request__pack
                     (const Nebula__AccountStatusRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__account_status_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__account_status_request__pack_to_buffer
                     (const Nebula__AccountStatusRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__account_status_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__AccountStatusRequest *
       nebula__account_status_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__AccountStatusRequest *)
     protobuf_c_message_unpack (&nebula__account_status_request__descriptor,
                                allocator, len, data);
}
void   nebula__account_status_request__free_unpacked
                     (Nebula__AccountStatusRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__account_status_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__account_status_response__account_status__init
                     (Nebula__AccountStatusResponse__AccountStatus         *message)
{
  static Nebula__AccountStatusResponse__AccountStatus init_value = NEBULA__ACCOUNT_STATUS_RESPONSE__ACCOUNT_STATUS__INIT;
  *message = init_value;
}
void   nebula__account_status_response__init
                     (Nebula__AccountStatusResponse         *message)
{
  static Nebula__AccountStatusResponse init_value = NEBULA__ACCOUNT_STATUS_RESPONSE__INIT;
  *message = init_value;
}
size_t nebula__account_status_response__get_packed_size
                     (const Nebula__AccountStatusResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__account_status_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__account_status_response__pack
                     (const Nebula__AccountStatusResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__account_status_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__account_status_response__pack_to_buffer
                     (const Nebula__AccountStatusResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__account_status_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__AccountStatusResponse *
       nebula__account_status_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__AccountStatusResponse *)
     protobuf_c_message_unpack (&nebula__account_status_response__descriptor,
                                allocator, len, data);
}
void   nebula__account_status_response__free_unpacked
                     (Nebula__AccountStatusResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__account_status_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__address__init
                     (Nebula__Address         *message)
{
  static Nebula__Address init_value = NEBULA__ADDRESS__INIT;
  *message = init_value;
}
size_t nebula__address__get_packed_size
                     (const Nebula__Address *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__address__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__address__pack
                     (const Nebula__Address *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__address__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__address__pack_to_buffer
                     (const Nebula__Address *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__address__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__Address *
       nebula__address__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__Address *)
     protobuf_c_message_unpack (&nebula__address__descriptor,
                                allocator, len, data);
}
void   nebula__address__free_unpacked
                     (Nebula__Address *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__address__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__dialog_request__init
                     (Nebula__DialogRequest         *message)
{
  static Nebula__DialogRequest init_value = NEBULA__DIALOG_REQUEST__INIT;
  *message = init_value;
}
size_t nebula__dialog_request__get_packed_size
                     (const Nebula__DialogRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__dialog_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__dialog_request__pack
                     (const Nebula__DialogRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__dialog_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__dialog_request__pack_to_buffer
                     (const Nebula__DialogRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__dialog_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__DialogRequest *
       nebula__dialog_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__DialogRequest *)
     protobuf_c_message_unpack (&nebula__dialog_request__descriptor,
                                allocator, len, data);
}
void   nebula__dialog_request__free_unpacked
                     (Nebula__DialogRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__dialog_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nebula__dialog_response__init
                     (Nebula__DialogResponse         *message)
{
  static Nebula__DialogResponse init_value = NEBULA__DIALOG_RESPONSE__INIT;
  *message = init_value;
}
size_t nebula__dialog_response__get_packed_size
                     (const Nebula__DialogResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__dialog_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__dialog_response__pack
                     (const Nebula__DialogResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__dialog_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__dialog_response__pack_to_buffer
                     (const Nebula__DialogResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__dialog_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__DialogResponse *
       nebula__dialog_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__DialogResponse *)
     protobuf_c_message_unpack (&nebula__dialog_response__descriptor,
                                allocator, len, data);
}
void   nebula__dialog_response__free_unpacked
                     (Nebula__DialogResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__dialog_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nebula__param__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__Param, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__Param, value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__param__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange nebula__param__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nebula__param__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.Param",
  "Param",
  "Nebula__Param",
  "Nebula",
  sizeof(Nebula__Param),
  2,
  nebula__param__field_descriptors,
  nebula__param__field_indices_by_name,
  1,  nebula__param__number_ranges,
  (ProtobufCMessageInit) nebula__param__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__account_update_request__field_descriptors[3] =
{
  {
    "flyme_uid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__AccountUpdateRequest, flyme_uid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__AccountUpdateRequest, phone),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "capability",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Nebula__AccountUpdateRequest, has_capability),
    PROTOBUF_C_OFFSETOF(Nebula__AccountUpdateRequest, capability),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__account_update_request__field_indices_by_name[] = {
  2,   /* field[2] = capability */
  0,   /* field[0] = flyme_uid */
  1,   /* field[1] = phone */
};
static const ProtobufCIntRange nebula__account_update_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor nebula__account_update_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.AccountUpdateRequest",
  "AccountUpdateRequest",
  "Nebula__AccountUpdateRequest",
  "Nebula",
  sizeof(Nebula__AccountUpdateRequest),
  3,
  nebula__account_update_request__field_descriptors,
  nebula__account_update_request__field_indices_by_name,
  1,  nebula__account_update_request__number_ranges,
  (ProtobufCMessageInit) nebula__account_update_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__account_update_response__field_descriptors[5] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__AccountUpdateResponse, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flyme_uid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__AccountUpdateResponse, flyme_uid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imsi",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__AccountUpdateResponse, imsi),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__AccountUpdateResponse, phone),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "capability",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Nebula__AccountUpdateResponse, has_capability),
    PROTOBUF_C_OFFSETOF(Nebula__AccountUpdateResponse, capability),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__account_update_response__field_indices_by_name[] = {
  4,   /* field[4] = capability */
  1,   /* field[1] = flyme_uid */
  2,   /* field[2] = imsi */
  3,   /* field[3] = phone */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange nebula__account_update_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor nebula__account_update_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.AccountUpdateResponse",
  "AccountUpdateResponse",
  "Nebula__AccountUpdateResponse",
  "Nebula",
  sizeof(Nebula__AccountUpdateResponse),
  5,
  nebula__account_update_response__field_descriptors,
  nebula__account_update_response__field_indices_by_name,
  1,  nebula__account_update_response__number_ranges,
  (ProtobufCMessageInit) nebula__account_update_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue nebula__auth_request__algorithm__enum_values_by_number[3] =
{
  { "MD5_MEIZU", "NEBULA__AUTH_REQUEST__ALGORITHM__MD5_MEIZU", 0 },
  { "MD5_DAA", "NEBULA__AUTH_REQUEST__ALGORITHM__MD5_DAA", 1 },
  { "MD5_FLYME", "NEBULA__AUTH_REQUEST__ALGORITHM__MD5_FLYME", 2 },
};
static const ProtobufCIntRange nebula__auth_request__algorithm__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex nebula__auth_request__algorithm__enum_values_by_name[3] =
{
  { "MD5_DAA", 1 },
  { "MD5_FLYME", 2 },
  { "MD5_MEIZU", 0 },
};
const ProtobufCEnumDescriptor nebula__auth_request__algorithm__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "Nebula.AuthRequest.Algorithm",
  "Algorithm",
  "Nebula__AuthRequest__Algorithm",
  "Nebula",
  3,
  nebula__auth_request__algorithm__enum_values_by_number,
  3,
  nebula__auth_request__algorithm__enum_values_by_name,
  1,
  nebula__auth_request__algorithm__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor nebula__auth_request__field_descriptors[7] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__AuthRequest, uid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "username",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__AuthRequest, username),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__AuthRequest, nonce),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "realm",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__AuthRequest, realm),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__AuthRequest, token),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "algorithm",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Nebula__AuthRequest, has_algorithm),
    PROTOBUF_C_OFFSETOF(Nebula__AuthRequest, algorithm),
    &nebula__auth_request__algorithm__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "other_info",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Nebula__AuthRequest, n_other_info),
    PROTOBUF_C_OFFSETOF(Nebula__AuthRequest, other_info),
    &nebula__param__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__auth_request__field_indices_by_name[] = {
  5,   /* field[5] = algorithm */
  2,   /* field[2] = nonce */
  6,   /* field[6] = other_info */
  3,   /* field[3] = realm */
  4,   /* field[4] = token */
  0,   /* field[0] = uid */
  1,   /* field[1] = username */
};
static const ProtobufCIntRange nebula__auth_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor nebula__auth_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.AuthRequest",
  "AuthRequest",
  "Nebula__AuthRequest",
  "Nebula",
  sizeof(Nebula__AuthRequest),
  7,
  nebula__auth_request__field_descriptors,
  nebula__auth_request__field_indices_by_name,
  1,  nebula__auth_request__number_ranges,
  (ProtobufCMessageInit) nebula__auth_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__auth_response__field_descriptors[3] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Nebula__AuthResponse, has_status),
    PROTOBUF_C_OFFSETOF(Nebula__AuthResponse, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__AuthResponse, nonce),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "realm",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__AuthResponse, realm),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__auth_response__field_indices_by_name[] = {
  1,   /* field[1] = nonce */
  2,   /* field[2] = realm */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange nebula__auth_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor nebula__auth_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.AuthResponse",
  "AuthResponse",
  "Nebula__AuthResponse",
  "Nebula",
  sizeof(Nebula__AuthResponse),
  3,
  nebula__auth_response__field_descriptors,
  nebula__auth_response__field_indices_by_name,
  1,  nebula__auth_response__number_ranges,
  (ProtobufCMessageInit) nebula__auth_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue nebula__message__content__msg_type__enum_values_by_number[3] =
{
  { "ePushMessage", "NEBULA__MESSAGE__CONTENT__MSG_TYPE__EPUSHMESSAGE", 0 },
  { "ePresenceMessage", "NEBULA__MESSAGE__CONTENT__MSG_TYPE__EPRESENCEMESSAGE", 1 },
  { "eSmsMessage", "NEBULA__MESSAGE__CONTENT__MSG_TYPE__ESMSMESSAGE", 2 },
};
static const ProtobufCIntRange nebula__message__content__msg_type__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex nebula__message__content__msg_type__enum_values_by_name[3] =
{
  { "ePresenceMessage", 1 },
  { "ePushMessage", 0 },
  { "eSmsMessage", 2 },
};
const ProtobufCEnumDescriptor nebula__message__content__msg_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "Nebula.Message.Content.MsgType",
  "MsgType",
  "Nebula__Message__Content__MsgType",
  "Nebula",
  3,
  nebula__message__content__msg_type__enum_values_by_number,
  3,
  nebula__message__content__msg_type__enum_values_by_name,
  1,
  nebula__message__content__msg_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor nebula__message__content__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__Message__Content, type),
    &nebula__message__content__msg_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "account",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__Message__Content, account),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__Message__Content, seq),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nebula__Message__Content, has_body),
    PROTOBUF_C_OFFSETOF(Nebula__Message__Content, body),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__message__content__field_indices_by_name[] = {
  1,   /* field[1] = account */
  3,   /* field[3] = body */
  2,   /* field[2] = seq */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange nebula__message__content__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor nebula__message__content__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.Message.Content",
  "Content",
  "Nebula__Message__Content",
  "Nebula",
  sizeof(Nebula__Message__Content),
  4,
  nebula__message__content__field_descriptors,
  nebula__message__content__field_indices_by_name,
  1,  nebula__message__content__number_ranges,
  (ProtobufCMessageInit) nebula__message__content__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue nebula__message__flag__enum_values_by_number[2] =
{
  { "MESSAGE_ACK", "NEBULA__MESSAGE__FLAG__MESSAGE_ACK", 1 },
  { "MESSAGE_END", "NEBULA__MESSAGE__FLAG__MESSAGE_END", 2 },
};
static const ProtobufCIntRange nebula__message__flag__value_ranges[] = {
{1, 0},{0, 2}
};
const ProtobufCEnumValueIndex nebula__message__flag__enum_values_by_name[2] =
{
  { "MESSAGE_ACK", 0 },
  { "MESSAGE_END", 1 },
};
const ProtobufCEnumDescriptor nebula__message__flag__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "Nebula.Message.Flag",
  "Flag",
  "Nebula__Message__Flag",
  "Nebula",
  2,
  nebula__message__flag__enum_values_by_number,
  2,
  nebula__message__flag__enum_values_by_name,
  1,
  nebula__message__flag__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor nebula__message__field_descriptors[2] =
{
  {
    "content",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Nebula__Message, n_content),
    PROTOBUF_C_OFFSETOF(Nebula__Message, content),
    &nebula__message__content__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flag",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Nebula__Message, has_flag),
    PROTOBUF_C_OFFSETOF(Nebula__Message, flag),
    &nebula__message__flag__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__message__field_indices_by_name[] = {
  0,   /* field[0] = content */
  1,   /* field[1] = flag */
};
static const ProtobufCIntRange nebula__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nebula__message__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.Message",
  "Message",
  "Nebula__Message",
  "Nebula",
  sizeof(Nebula__Message),
  2,
  nebula__message__field_descriptors,
  nebula__message__field_indices_by_name,
  1,  nebula__message__number_ranges,
  (ProtobufCMessageInit) nebula__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__message_seq__content__field_descriptors[2] =
{
  {
    "account",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__MessageSeq__Content, account),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__MessageSeq__Content, seq),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__message_seq__content__field_indices_by_name[] = {
  0,   /* field[0] = account */
  1,   /* field[1] = seq */
};
static const ProtobufCIntRange nebula__message_seq__content__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nebula__message_seq__content__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.MessageSeq.Content",
  "Content",
  "Nebula__MessageSeq__Content",
  "Nebula",
  sizeof(Nebula__MessageSeq__Content),
  2,
  nebula__message_seq__content__field_descriptors,
  nebula__message_seq__content__field_indices_by_name,
  1,  nebula__message_seq__content__number_ranges,
  (ProtobufCMessageInit) nebula__message_seq__content__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__message_seq__field_descriptors[1] =
{
  {
    "content",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Nebula__MessageSeq, n_content),
    PROTOBUF_C_OFFSETOF(Nebula__MessageSeq, content),
    &nebula__message_seq__content__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__message_seq__field_indices_by_name[] = {
  0,   /* field[0] = content */
};
static const ProtobufCIntRange nebula__message_seq__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nebula__message_seq__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.MessageSeq",
  "MessageSeq",
  "Nebula__MessageSeq",
  "Nebula",
  sizeof(Nebula__MessageSeq),
  1,
  nebula__message_seq__field_descriptors,
  nebula__message_seq__field_indices_by_name,
  1,  nebula__message_seq__number_ranges,
  (ProtobufCMessageInit) nebula__message_seq__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__message_kiev_ack__field_descriptors[2] =
{
  {
    "seqs",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__MessageKievAck, seqs),
    &nebula__message_seq__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__MessageKievAck, index),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__message_kiev_ack__field_indices_by_name[] = {
  1,   /* field[1] = index */
  0,   /* field[0] = seqs */
};
static const ProtobufCIntRange nebula__message_kiev_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nebula__message_kiev_ack__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.MessageKievAck",
  "MessageKievAck",
  "Nebula__MessageKievAck",
  "Nebula",
  sizeof(Nebula__MessageKievAck),
  2,
  nebula__message_kiev_ack__field_descriptors,
  nebula__message_kiev_ack__field_indices_by_name,
  1,  nebula__message_kiev_ack__number_ranges,
  (ProtobufCMessageInit) nebula__message_kiev_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__subscribe_request__field_descriptors[1] =
{
  {
    "app",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(Nebula__SubscribeRequest, n_app),
    PROTOBUF_C_OFFSETOF(Nebula__SubscribeRequest, app),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__subscribe_request__field_indices_by_name[] = {
  0,   /* field[0] = app */
};
static const ProtobufCIntRange nebula__subscribe_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nebula__subscribe_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.SubscribeRequest",
  "SubscribeRequest",
  "Nebula__SubscribeRequest",
  "Nebula",
  sizeof(Nebula__SubscribeRequest),
  1,
  nebula__subscribe_request__field_descriptors,
  nebula__subscribe_request__field_indices_by_name,
  1,  nebula__subscribe_request__number_ranges,
  (ProtobufCMessageInit) nebula__subscribe_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__subscribe_response__content__field_descriptors[3] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Nebula__SubscribeResponse__Content, has_status),
    PROTOBUF_C_OFFSETOF(Nebula__SubscribeResponse__Content, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__SubscribeResponse__Content, app),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pushid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__SubscribeResponse__Content, pushid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__subscribe_response__content__field_indices_by_name[] = {
  1,   /* field[1] = app */
  2,   /* field[2] = pushid */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange nebula__subscribe_response__content__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor nebula__subscribe_response__content__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.SubscribeResponse.Content",
  "Content",
  "Nebula__SubscribeResponse__Content",
  "Nebula",
  sizeof(Nebula__SubscribeResponse__Content),
  3,
  nebula__subscribe_response__content__field_descriptors,
  nebula__subscribe_response__content__field_indices_by_name,
  1,  nebula__subscribe_response__content__number_ranges,
  (ProtobufCMessageInit) nebula__subscribe_response__content__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__subscribe_response__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__SubscribeResponse, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Nebula__SubscribeResponse, n_content),
    PROTOBUF_C_OFFSETOF(Nebula__SubscribeResponse, content),
    &nebula__subscribe_response__content__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__subscribe_response__field_indices_by_name[] = {
  1,   /* field[1] = content */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange nebula__subscribe_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nebula__subscribe_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.SubscribeResponse",
  "SubscribeResponse",
  "Nebula__SubscribeResponse",
  "Nebula",
  sizeof(Nebula__SubscribeResponse),
  2,
  nebula__subscribe_response__field_descriptors,
  nebula__subscribe_response__field_indices_by_name,
  1,  nebula__subscribe_response__number_ranges,
  (ProtobufCMessageInit) nebula__subscribe_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__notify_body__field_descriptors[2] =
{
  {
    "app",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__NotifyBody, app),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__NotifyBody, body),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__notify_body__field_indices_by_name[] = {
  0,   /* field[0] = app */
  1,   /* field[1] = body */
};
static const ProtobufCIntRange nebula__notify_body__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nebula__notify_body__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.NotifyBody",
  "NotifyBody",
  "Nebula__NotifyBody",
  "Nebula",
  sizeof(Nebula__NotifyBody),
  2,
  nebula__notify_body__field_descriptors,
  nebula__notify_body__field_indices_by_name,
  1,  nebula__notify_body__number_ranges,
  (ProtobufCMessageInit) nebula__notify_body__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__sms_request__file_info__field_descriptors[4] =
{
  {
    "mimetype",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest__FileInfo, mimetype),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest__FileInfo, size),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filename",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest__FileInfo, filename),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "url",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest__FileInfo, url),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__sms_request__file_info__field_indices_by_name[] = {
  2,   /* field[2] = filename */
  0,   /* field[0] = mimetype */
  1,   /* field[1] = size */
  3,   /* field[3] = url */
};
static const ProtobufCIntRange nebula__sms_request__file_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor nebula__sms_request__file_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.SmsRequest.FileInfo",
  "FileInfo",
  "Nebula__SmsRequest__FileInfo",
  "Nebula",
  sizeof(Nebula__SmsRequest__FileInfo),
  4,
  nebula__sms_request__file_info__field_descriptors,
  nebula__sms_request__file_info__field_indices_by_name,
  1,  nebula__sms_request__file_info__number_ranges,
  (ProtobufCMessageInit) nebula__sms_request__file_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue nebula__sms_request__sms_type__enum_values_by_number[3] =
{
  { "eShortMessage", "NEBULA__SMS_REQUEST__SMS_TYPE__ESHORTMESSAGE", 0 },
  { "eMultimediaMessage", "NEBULA__SMS_REQUEST__SMS_TYPE__EMULTIMEDIAMESSAGE", 1 },
  { "eReportMessage", "NEBULA__SMS_REQUEST__SMS_TYPE__EREPORTMESSAGE", 2 },
};
static const ProtobufCIntRange nebula__sms_request__sms_type__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex nebula__sms_request__sms_type__enum_values_by_name[3] =
{
  { "eMultimediaMessage", 1 },
  { "eReportMessage", 2 },
  { "eShortMessage", 0 },
};
const ProtobufCEnumDescriptor nebula__sms_request__sms_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "Nebula.SmsRequest.SmsType",
  "SmsType",
  "Nebula__SmsRequest__SmsType",
  "Nebula",
  3,
  nebula__sms_request__sms_type__enum_values_by_number,
  3,
  nebula__sms_request__sms_type__enum_values_by_name,
  1,
  nebula__sms_request__sms_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue nebula__sms_request__report_type__enum_values_by_number[2] =
{
  { "eSMSReport", "NEBULA__SMS_REQUEST__REPORT_TYPE__ESMSREPORT", 0 },
  { "eMMSReport", "NEBULA__SMS_REQUEST__REPORT_TYPE__EMMSREPORT", 1 },
};
static const ProtobufCIntRange nebula__sms_request__report_type__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex nebula__sms_request__report_type__enum_values_by_name[2] =
{
  { "eMMSReport", 1 },
  { "eSMSReport", 0 },
};
const ProtobufCEnumDescriptor nebula__sms_request__report_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "Nebula.SmsRequest.ReportType",
  "ReportType",
  "Nebula__SmsRequest__ReportType",
  "Nebula",
  2,
  nebula__sms_request__report_type__enum_values_by_number,
  2,
  nebula__sms_request__report_type__enum_values_by_name,
  1,
  nebula__sms_request__report_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor nebula__sms_request__field_descriptors[14] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, type),
    &nebula__sms_request__sms_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, msgid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, src),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, n_dst),
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, dst),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, has_body),
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, body),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "report_flag",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, has_report_flag),
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, report_flag),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "report_type",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, has_report_type),
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, report_type),
    &nebula__sms_request__report_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "report_status",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, report_status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, time),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expires",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, expires),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pdu",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, pdu),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, has_size),
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, size),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ver",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, ver),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fileinfos",
    14,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, n_fileinfos),
    PROTOBUF_C_OFFSETOF(Nebula__SmsRequest, fileinfos),
    &nebula__sms_request__file_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__sms_request__field_indices_by_name[] = {
  4,   /* field[4] = body */
  3,   /* field[3] = dst */
  9,   /* field[9] = expires */
  13,   /* field[13] = fileinfos */
  1,   /* field[1] = msgid */
  10,   /* field[10] = pdu */
  5,   /* field[5] = report_flag */
  7,   /* field[7] = report_status */
  6,   /* field[6] = report_type */
  11,   /* field[11] = size */
  2,   /* field[2] = src */
  8,   /* field[8] = time */
  0,   /* field[0] = type */
  12,   /* field[12] = ver */
};
static const ProtobufCIntRange nebula__sms_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor nebula__sms_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.SmsRequest",
  "SmsRequest",
  "Nebula__SmsRequest",
  "Nebula",
  sizeof(Nebula__SmsRequest),
  14,
  nebula__sms_request__field_descriptors,
  nebula__sms_request__field_indices_by_name,
  1,  nebula__sms_request__number_ranges,
  (ProtobufCMessageInit) nebula__sms_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__sms_response__field_descriptors[2] =
{
  {
    "msgid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__SmsResponse, msgid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__SmsResponse, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__sms_response__field_indices_by_name[] = {
  0,   /* field[0] = msgid */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange nebula__sms_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nebula__sms_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.SmsResponse",
  "SmsResponse",
  "Nebula__SmsResponse",
  "Nebula",
  sizeof(Nebula__SmsResponse),
  2,
  nebula__sms_response__field_descriptors,
  nebula__sms_response__field_indices_by_name,
  1,  nebula__sms_response__number_ranges,
  (ProtobufCMessageInit) nebula__sms_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__presence_notify__content__field_descriptors[3] =
{
  {
    "account",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__PresenceNotify__Content, account),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "capability",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Nebula__PresenceNotify__Content, has_capability),
    PROTOBUF_C_OFFSETOF(Nebula__PresenceNotify__Content, capability),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Nebula__PresenceNotify__Content, has_status),
    PROTOBUF_C_OFFSETOF(Nebula__PresenceNotify__Content, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__presence_notify__content__field_indices_by_name[] = {
  0,   /* field[0] = account */
  1,   /* field[1] = capability */
  2,   /* field[2] = status */
};
static const ProtobufCIntRange nebula__presence_notify__content__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor nebula__presence_notify__content__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.PresenceNotify.Content",
  "Content",
  "Nebula__PresenceNotify__Content",
  "Nebula",
  sizeof(Nebula__PresenceNotify__Content),
  3,
  nebula__presence_notify__content__field_descriptors,
  nebula__presence_notify__content__field_indices_by_name,
  1,  nebula__presence_notify__content__number_ranges,
  (ProtobufCMessageInit) nebula__presence_notify__content__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__presence_notify__field_descriptors[1] =
{
  {
    "content",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Nebula__PresenceNotify, n_content),
    PROTOBUF_C_OFFSETOF(Nebula__PresenceNotify, content),
    &nebula__presence_notify__content__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__presence_notify__field_indices_by_name[] = {
  0,   /* field[0] = content */
};
static const ProtobufCIntRange nebula__presence_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nebula__presence_notify__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.PresenceNotify",
  "PresenceNotify",
  "Nebula__PresenceNotify",
  "Nebula",
  sizeof(Nebula__PresenceNotify),
  1,
  nebula__presence_notify__field_descriptors,
  nebula__presence_notify__field_indices_by_name,
  1,  nebula__presence_notify__number_ranges,
  (ProtobufCMessageInit) nebula__presence_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__presence_request__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Nebula__PresenceRequest, has_type),
    PROTOBUF_C_OFFSETOF(Nebula__PresenceRequest, type),
    &nebula__presence_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Nebula__PresenceRequest, has_sequence),
    PROTOBUF_C_OFFSETOF(Nebula__PresenceRequest, sequence),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "account",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(Nebula__PresenceRequest, n_account),
    PROTOBUF_C_OFFSETOF(Nebula__PresenceRequest, account),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__presence_request__field_indices_by_name[] = {
  2,   /* field[2] = account */
  1,   /* field[1] = sequence */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange nebula__presence_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor nebula__presence_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.PresenceRequest",
  "PresenceRequest",
  "Nebula__PresenceRequest",
  "Nebula",
  sizeof(Nebula__PresenceRequest),
  3,
  nebula__presence_request__field_descriptors,
  nebula__presence_request__field_indices_by_name,
  1,  nebula__presence_request__number_ranges,
  (ProtobufCMessageInit) nebula__presence_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__presence_response__field_descriptors[4] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__PresenceResponse, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Nebula__PresenceResponse, has_type),
    PROTOBUF_C_OFFSETOF(Nebula__PresenceResponse, type),
    &nebula__presence_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Nebula__PresenceResponse, has_sequence),
    PROTOBUF_C_OFFSETOF(Nebula__PresenceResponse, sequence),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "account",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(Nebula__PresenceResponse, n_account),
    PROTOBUF_C_OFFSETOF(Nebula__PresenceResponse, account),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__presence_response__field_indices_by_name[] = {
  3,   /* field[3] = account */
  2,   /* field[2] = sequence */
  0,   /* field[0] = status */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange nebula__presence_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor nebula__presence_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.PresenceResponse",
  "PresenceResponse",
  "Nebula__PresenceResponse",
  "Nebula",
  sizeof(Nebula__PresenceResponse),
  4,
  nebula__presence_response__field_descriptors,
  nebula__presence_response__field_indices_by_name,
  1,  nebula__presence_response__number_ranges,
  (ProtobufCMessageInit) nebula__presence_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__account_status_request__field_descriptors[1] =
{
  {
    "account",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(Nebula__AccountStatusRequest, n_account),
    PROTOBUF_C_OFFSETOF(Nebula__AccountStatusRequest, account),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__account_status_request__field_indices_by_name[] = {
  0,   /* field[0] = account */
};
static const ProtobufCIntRange nebula__account_status_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nebula__account_status_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.AccountStatusRequest",
  "AccountStatusRequest",
  "Nebula__AccountStatusRequest",
  "Nebula",
  sizeof(Nebula__AccountStatusRequest),
  1,
  nebula__account_status_request__field_descriptors,
  nebula__account_status_request__field_indices_by_name,
  1,  nebula__account_status_request__number_ranges,
  (ProtobufCMessageInit) nebula__account_status_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__account_status_response__account_status__field_descriptors[3] =
{
  {
    "account",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__AccountStatusResponse__AccountStatus, account),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Nebula__AccountStatusResponse__AccountStatus, has_status),
    PROTOBUF_C_OFFSETOF(Nebula__AccountStatusResponse__AccountStatus, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "capability",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Nebula__AccountStatusResponse__AccountStatus, has_capability),
    PROTOBUF_C_OFFSETOF(Nebula__AccountStatusResponse__AccountStatus, capability),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__account_status_response__account_status__field_indices_by_name[] = {
  0,   /* field[0] = account */
  2,   /* field[2] = capability */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange nebula__account_status_response__account_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor nebula__account_status_response__account_status__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.AccountStatusResponse.AccountStatus",
  "AccountStatus",
  "Nebula__AccountStatusResponse__AccountStatus",
  "Nebula",
  sizeof(Nebula__AccountStatusResponse__AccountStatus),
  3,
  nebula__account_status_response__account_status__field_descriptors,
  nebula__account_status_response__account_status__field_indices_by_name,
  1,  nebula__account_status_response__account_status__number_ranges,
  (ProtobufCMessageInit) nebula__account_status_response__account_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__account_status_response__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__AccountStatusResponse, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Nebula__AccountStatusResponse, n_result),
    PROTOBUF_C_OFFSETOF(Nebula__AccountStatusResponse, result),
    &nebula__account_status_response__account_status__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__account_status_response__field_indices_by_name[] = {
  1,   /* field[1] = result */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange nebula__account_status_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nebula__account_status_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.AccountStatusResponse",
  "AccountStatusResponse",
  "Nebula__AccountStatusResponse",
  "Nebula",
  sizeof(Nebula__AccountStatusResponse),
  2,
  nebula__account_status_response__field_descriptors,
  nebula__account_status_response__field_indices_by_name,
  1,  nebula__account_status_response__number_ranges,
  (ProtobufCMessageInit) nebula__account_status_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__address__field_descriptors[2] =
{
  {
    "host",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__Address, host),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__Address, port),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__address__field_indices_by_name[] = {
  0,   /* field[0] = host */
  1,   /* field[1] = port */
};
static const ProtobufCIntRange nebula__address__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nebula__address__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.Address",
  "Address",
  "Nebula__Address",
  "Nebula",
  sizeof(Nebula__Address),
  2,
  nebula__address__field_descriptors,
  nebula__address__field_indices_by_name,
  1,  nebula__address__number_ranges,
  (ProtobufCMessageInit) nebula__address__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__dialog_request__field_descriptors[4] =
{
  {
    "src",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__DialogRequest, src),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__DialogRequest, dst),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dialog",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__DialogRequest, dialog),
    &nebula__address__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nebula__DialogRequest, has_body),
    PROTOBUF_C_OFFSETOF(Nebula__DialogRequest, body),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__dialog_request__field_indices_by_name[] = {
  3,   /* field[3] = body */
  2,   /* field[2] = dialog */
  1,   /* field[1] = dst */
  0,   /* field[0] = src */
};
static const ProtobufCIntRange nebula__dialog_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor nebula__dialog_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.DialogRequest",
  "DialogRequest",
  "Nebula__DialogRequest",
  "Nebula",
  sizeof(Nebula__DialogRequest),
  4,
  nebula__dialog_request__field_descriptors,
  nebula__dialog_request__field_indices_by_name,
  1,  nebula__dialog_request__number_ranges,
  (ProtobufCMessageInit) nebula__dialog_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nebula__dialog_response__field_descriptors[5] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__DialogResponse, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__DialogResponse, src),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__DialogResponse, dst),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dialog",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__DialogResponse, dialog),
    &nebula__address__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nebula__DialogResponse, has_body),
    PROTOBUF_C_OFFSETOF(Nebula__DialogResponse, body),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__dialog_response__field_indices_by_name[] = {
  4,   /* field[4] = body */
  3,   /* field[3] = dialog */
  2,   /* field[2] = dst */
  1,   /* field[1] = src */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange nebula__dialog_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor nebula__dialog_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.DialogResponse",
  "DialogResponse",
  "Nebula__DialogResponse",
  "Nebula",
  sizeof(Nebula__DialogResponse),
  5,
  nebula__dialog_response__field_descriptors,
  nebula__dialog_response__field_indices_by_name,
  1,  nebula__dialog_response__number_ranges,
  (ProtobufCMessageInit) nebula__dialog_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue nebula__presence_type__enum_values_by_number[3] =
{
  { "eIncrementSubscribe", "NEBULA__PRESENCE_TYPE__EINCREMENTSUBSCRIBE", 0 },
  { "eFullSubscribe", "NEBULA__PRESENCE_TYPE__EFULLSUBSCRIBE", 1 },
  { "eUnSubscribe", "NEBULA__PRESENCE_TYPE__EUNSUBSCRIBE", 2 },
};
static const ProtobufCIntRange nebula__presence_type__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex nebula__presence_type__enum_values_by_name[3] =
{
  { "eFullSubscribe", 1 },
  { "eIncrementSubscribe", 0 },
  { "eUnSubscribe", 2 },
};
const ProtobufCEnumDescriptor nebula__presence_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "Nebula.PresenceType",
  "PresenceType",
  "Nebula__PresenceType",
  "Nebula",
  3,
  nebula__presence_type__enum_values_by_number,
  3,
  nebula__presence_type__enum_values_by_name,
  1,
  nebula__presence_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
