/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "nebula.pb-c.h"
void   nebula__nebula_msg__init
                     (Nebula__NebulaMsg         *message)
{
  static Nebula__NebulaMsg init_value = NEBULA__NEBULA_MSG__INIT;
  *message = init_value;
}
size_t nebula__nebula_msg__get_packed_size
                     (const Nebula__NebulaMsg *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__nebula_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nebula__nebula_msg__pack
                     (const Nebula__NebulaMsg *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__nebula_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nebula__nebula_msg__pack_to_buffer
                     (const Nebula__NebulaMsg *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__nebula_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nebula__NebulaMsg *
       nebula__nebula_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nebula__NebulaMsg *)
     protobuf_c_message_unpack (&nebula__nebula_msg__descriptor,
                                allocator, len, data);
}
void   nebula__nebula_msg__free_unpacked
                     (Nebula__NebulaMsg *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &nebula__nebula_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nebula__nebula_msg__field_descriptors[2] =
{
  {
    "msgid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Nebula__NebulaMsg, msgid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Nebula__NebulaMsg, has_body),
    PROTOBUF_C_OFFSETOF(Nebula__NebulaMsg, body),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nebula__nebula_msg__field_indices_by_name[] = {
  1,   /* field[1] = body */
  0,   /* field[0] = msgid */
};
static const ProtobufCIntRange nebula__nebula_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nebula__nebula_msg__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Nebula.NebulaMsg",
  "NebulaMsg",
  "Nebula__NebulaMsg",
  "Nebula",
  sizeof(Nebula__NebulaMsg),
  2,
  nebula__nebula_msg__field_descriptors,
  nebula__nebula_msg__field_indices_by_name,
  1,  nebula__nebula_msg__number_ranges,
  (ProtobufCMessageInit) nebula__nebula_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
